spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
  main:
    allow-bean-definition-overriding: true

lotto:
  result-checker:
    lotteryRunOccurrence: "0 55 11 * * 6"
  number-generator:
    lotteryRunOccurrence: "0 0 12 * * 6"
    facade:
      count: 25
      lower-band: 1
      upper-band: 99
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
          connectionTimeout: 5000
          readTimeout: 5000
